# Generated by Django 2.2.2 on 2019-09-20 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=288)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(default='Pending', max_length=10)),
                ('payment_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone_no', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='sp',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('phone_no', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('time_start_h', models.CharField(max_length=2)),
                ('time_start_m', models.CharField(max_length=2)),
                ('time_end_h', models.CharField(max_length=2)),
                ('time_end_m', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('day', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('image', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=10)),
                ('stype', models.CharField(max_length=10)),
                ('phone_no', models.CharField(default='', max_length=10)),
                ('cost', models.FloatField(default=0)),
                ('providerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.sp')),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_and_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=10)),
                ('amount', models.FloatField()),
                ('appointmentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.appointment')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='clientid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.client'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='serviceid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.service'),
        ),
    ]
