# Generated by Django 2.2.2 on 2019-09-20 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='admin_local',
        ),
    ]
